scrabill/how-many-days-until-halloween

index.html
=> Adding link to the repo

js/script.js
Closes #5 
Added an if/else to check if it is October, and then added text to say "check bak in October!" if the month is not October.
=> condition to check if it is October

contributer-list.md
closes #20 
If there is anything you would like changed, I would be happy to make any editss!
=> added contributors list

CONTRIBUTING.md
=> Corrected spelling mistakes.

js/script.js
Reverts scrabill/how-many-days-until-halloween#12
Looks like I broke the previously added functionality with this merge. Will have to fix this.
=> Revert "Enhancement: Randomize <h2> text on page load"

contributer-list.md
Added my name to contributer-list.md as directed in guidelines.
=> Added my name to contributers list

css/styles.css, index.html
Hi there! I picked out some fun fonts for your text. ~Em
=> updated with spooky fonts

README.md
=> Add link to contributor list

contributer-list.md
Updated spelling of contributors
=> Updated spelling

contributer-list.md
Added virenb to the contributor list
=> Added myself to the contributor list

README.md
This, I hope, "fixes" Issue #33
=> My First PR for Issue #33.

contributer-list.md
Add link style and https to urls in author links
=> Update contributor list's author links and model

contributer-list.md, css/styles.css, index.html, js/spookymain.js
#32 
#1 
Also, might want to add Visual Studio Code to the list of code/text editors.
=> Documentation and enhancements 

CODE_OF_CONDUCT.md
This Code of Conduct is adapted from the Contributor Covenant, version 1.4.
=> File added: CODE_OF_CONDUCT.md

README.md
@scrabill Made a teeny update to the README
=> Added link to changelog

js/spookymain.js
Hey, @scrabill 
Please approve this pull request
Spooky text - 
"When black cats prowl and pumpkins gleam, May luck be yours on Halloween"
Thanks!
=> Added New Spooky text

js/spookymain.js
Extending #79 
I was too spooked to add more phrases.
=> Add very spooky texts

README.md
Since Changelog.md and Contributing.md are already there, I added the code of conduct link.
=> Added code of conduct link.

css/styles.css, index.html
I have added fixes for #86 by adding a new class too the paragraph and giving it size 20. Hope that helps.
=> Fixes for issue #86

css/styles.css
font size increased to 40px, issue #86
=> font size increased

css/styles.css
- Fixing Broken CSS declaration block in styles.css
------
Please, before doing the PR make sure that you are following the intructions described in [CONTRIBUTING.md](https://github.com/scrabill/how-many-days-until-halloween/blob/master/CONTRIBUTING.md) and you have completed the following checklist
**Checklist**
Thanks for contributing
=> fixing broken css declaration block in styles.css

contributer-list.md, css/styles.css, js/spookymain.js
This PR also disables highlighting for aesthetic reasons.
=> Randomize splash text on click

js/spookymain.js
Task: #79 
Add some more spooky sentences to splashText variable
=> Add more spooky sentences to splashText variable

contributer-list.md
Task: Issue #123
Added link to contributors in contributors-list.md
=> Added link to contributors in contributors-list.md

css/styles.css
Updated styles.css to accommodate larger screen resolution
=> #86 Update header size for large screen

js/spookymain.js
Task: [Link to external story here.](link)
Added a line of spooky text!
Write down warnings here.
=> Added a line of spooky text

js/spookymain.js
Task: [Link to external story here.](link)
Describe your changes here.
Write down warnings here.
=> Added Halloween text

css/styles.css, index.html
Reverts scrabill/how-many-days-until-halloween#119
I think I broke something :(
=> Revert "Font amendments"

css/styles.css
Task: [Link to external story here.](link)
Describe your changes here.
Changed background color to opaque white when hovered and removed the blue outline when focused on the button.
Write down warnings here.
=> Improve toggle button experience

CONTRIBUTING.md
=> Contributing.md: Added instruction video for getting started

js/script.js
Just couldn't bear seeing a sentence ending without a punctuation mark. :P
=> Punctuation

index.html, js/script.js
=> Added secret Konami code easter egg

:, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
This is in reference to issue #147 
Fixed some typos and grammatical errors in README.md, CODE_OF_CONDUCT.md and CONTRIBUTING.md
=> Deleted : file and fixed some typos

.eslintrc.js, README.md, css/styles.css, index.html, js/script.js
Hi there!
Decided to took a little warming trip to Hacktoberfest and implemented this project with [Moment.js](https://momentjs.com/). Check the message for extra spookiness. 😉
How do you like it?
=> Use Moment.js library for calculation

css/styles.css, index.html, js/script.js
Added an H3 with some random Halloween facts. Adding to the facts array could be an opportunity for some first time pull requests.
=> Added random Halloween facts and adjusted styles

README.md
- [ x ] New feature (non-breaking change which adds new functionality)
Added the following shields from https://shields.io:
* Custom shield: Friendly - True
** Intended for marking repo as friendly to contributors
* Github Contributors
** Reinforces the friendly badge before it by showing the number of contributors
* GitHub commit activity the past week, 4 weeks, year
* GitHub last commit
#174: Improvement: Add sheilds to README.md
None
Tested via python -m SimpleHTTPServer, no issues found
No
=> Commit and Contributor shield additions to README.md

PULL_REQUEST_TEMPLATE.md, README.md
Original issue: #185 (add Technology section in README)
Original PR: #191 (bug in link syntax)
Changes in this PR:
- fixed the broken link syntax in the Technologies section
- some minor spelling and grammar edits in the Pull Request Template
=> fixed Technology links

CONTRIBUTING.md
Updated reference for link to egghead.io video.
Re: issue #163 
n/a
n/a
n/a
=> Update link reference

CONTRIBUTING.md
Fixed issue #206 and removed the fonts folder link from Contributing.md file
What …
=> Fixed issue #206

CONTRIBUTING.md
What tests were conducted to ensure the PR functions and has no impact on previous …
=> appended digital ocenan's how to raise pull request link for user help

js/script.js
The issue was that the difference was between the current time and 12 AM on 31st. Which is 5 days from now and not 6. So, a difference from the start of the days would be 6 days from today.
#218 
Was a straight forward one line change. Should pass the current tests and no  need for new tests.
None
=> Fix #218 for incorrect countdown to Halloween

index.html
Add Fork me on Github Corner
Only added a "fork me" corner ribbon to the page.
#207
None.
Visual inspection of the website to make sure it looks as expected.
None.
=> Add Fork me on Github Corner #207

js/script.js
On Halloween message has an extra space in the word "it 's" corrected it to "it's"
- [x ] Small bug fix (non-breaking change which fixes an issue)
Does the PR have a potential impact on performance on the codebase? If so, …
=> Removed Extra space

css/styles.css
Media queries were used to target the various mobile device sizes.
https://github.com/scrabill/how-many-days-until-halloween/issues/188
Does the PR have a potential impact on performance on the codebase? No.
This was tested via inspector in Firefox dev tools.
Have new dependencies been introduced? No.
=> Updated mobile styles to fill page.

js/script.js
Put jack-o-lantern emoji in the homepage.
=> Add jack-o-lantern emoji

js/script.js
No
Added few Halloween facts
Added facts to script.js
#226
No
NA
NA
=> Added few Halloween facts

js/script.js
=> added fun fact

js/script.js
=> Add more halloween facts

js/script.js
Added a few more facts to the Halloween facts array
Added 3 more facts to the fact array and 2 more sources
#226
=> Added a few more facts

js/script.js
=> 'added-more-facts'

js/script.js
#226 
What tests were conducted to ensure the PR functions have no impact on previous functionalities of the code base?
Have new dependencies been introduced? Please list them with links to documentation and add installation steps to the README.
=> added a few more halloween facts :tada:

js/script.js
Halloween_facts.
Added random halloween facts
#226
=> Added random halloween facts

js/script.js
This pull request adds a new Halloween fact to the loading list.
#226
=> Adds a new Halloween fact

js/script.js
=> Added a fact about Halloween.

js/script.js
Add just another halloween fact
Adds just another halloween fact.
Enhancement: Add a Halloween fact #226
=> adds a halloween fact

js/script.js
This PR is related to the issue #226 .
=> Add a Halloween fact: Fear of ghosts

js/script.js
=> Added a fact.

js/script.js
=> Added Costume Idea

js/script.js
=> Added Blessing in disguise costume idea Issue #253

js/script.js
=> New costume added (Ecce Homo)

js/script.js
Added a line to script.js to include an idea for a Kool-Aid man costume.
Enhancement: Add Halloween Costume Ideas #253
No
None
No
=> Updated script.js for new costume idea

js/script.js
=> Added new costume idea

js/script.js
=> Issue #226 - add a halloween fact

js/script.js
=> Add only before days until and exclamation to end

index.html, js/script.js
=> added a button to generate the next random fact.

js/script.js
Added some random Canadian facts!
Nope.
Canadian Halloween Facts
Edited src.js
#226 
Increase array size.
What tests were conducted to ensure the PR functions have no impact on previous functionalities of the code base?
None.
=> Added Halloween Facts!

js/script.js
As per issue #253, added four new costume ideas to the list of costumes; Spider-Man, Avocado Toast, Nerd, and One Night Stand.
N/A
To test, I cycled through the random costume suggestions in my browser and checked the links for all new additions to ensure the links were functioning as expected, and all new additions appeared in the random selection.
N/A
=> Added Four New Costume Ideas to the Costumes List

js/script.js
=> added incredibles costume idea line 205 issue 253

js/script.js
- [ x] New feature (non-breaking change which adds new functionality)
I added the costume idea to dress as the green Android bot
#253
None
None
No
=> Added halloween costume idea #253

js/script.js
Economic reference on Halloween.
Added a new fact into the array.
#226
=> Added new fact - economic point

js/script.js
Ghost relationship
Ghost relationship with human
#232
=> Ghost relationship

js/script.js
=> Add ceiling fan costume idea issue 253

js/script.js
- [x ] New feature (non-breaking change which adds new functionality)
What tests …
=> Adding a new halloween fact

js/script.js
Added Oscar Statue, and 3 Hole Punch Costume
What tests were conducted to ensure …
=> Added 2 New Costume Ideas

js/script.js
=> added new fact.

js/script.js
Two new costume ideas for #253 :
Ruth Vader Ginsburg: https://pbs.twimg.com/media/Dqn48iiX0AAOZKw.jpg
Pickle Rick: https://cdn-blog.adafruit.com/uploads/2017/08/Pickle-Rick-costume-360x480.jpg
Does the PR have a potential …
=> Add ruth vader ginsburg and pickle rick costume ideas

js/script.js
Adds a halloween fact
Adds a halloween fact
#284 
No
None
No
=> Adds halloween fact

js/script.js
Input a new Halloween fact in response to #226
Input 1 Halloween fact along with the source. 
#226 
N/A
N/A
N/A
=> Add a new halloween fact.

js/script.js
=> Added costume idea (Pumkin Spiced Clown) Issue #253

js/script.js
=> added my opinion fact

js/script.js
=> Adding the best cotume i've ever seen

js/script.js
=> add new fact

js/script.js
=> added The Cloud costume idea and fixed typo in Napoleon Dynamite idea

js/script.js
=> Added Slack Costume

js/script.js
=> added costume idea (identity theft)

js/script.js
=> added halloween costume on new branch

js/script.js
Fixed grammar/spelling mistake, added a Halloween fact/
What tests were conducted to ensure the PR functions have no impact on previous functionalities of the code base?
Have new dependencies been introduced? Please list them with links to documentation and …
=> Added Halloween fact!

README.md
Add shield, reference to issue #174
=> Add shield for halloween countdown in days

index.html
Reverts scrabill/how-many-days-until-halloween#369
=> Revert "Updated index.html"

css/styles.css, js/script.js
A subtle flashing "[num] days" text that includes the number to add to the spooky-ness.
Changes:
- added span tag to scripts.js
- added class and keyframe to styles.css
=> add subtle crimson flashing text

css/styles.css, index.html
I've added a fun little ghost that nips around the screen, keeping behind the text.
I'm happy to make changes if you think it could work better another way. The container div is positioned using viewport units to make it more responsive.
=> Add animated ghost behind text.

css/styles.css, js/script.js
=> tweak the front page
